import * as fs from "node:fs";
import * as path from "node:path";
import { compile } from "json-schema-to-typescript";

const ROOT = path.join(import.meta.dirname, "..");
const MODELS_DIR = path.join(ROOT, "lib", "models");
const TEMP_DIR = path.join(ROOT, "temp");

const BANNER = `/* eslint-disable */
/* biome-ignore: generated */
/**
 * Auto-generated by scripts/generateRequestTypes.ts — DO NOT EDIT.
 * Generated from lib/models/ JSON Schema files.
 */
\n`;

async function main() {
  const files = fs
    .readdirSync(MODELS_DIR, { withFileTypes: true })
    .filter((d) => d.isFile() && d.name.endsWith(".json"))
    .map((d) => d.name);

  if (!fs.existsSync(TEMP_DIR)) {
    fs.mkdirSync(TEMP_DIR, { recursive: true });
  }

  for (const file of files) {
    const schema = JSON.parse(
      fs.readFileSync(path.join(MODELS_DIR, file), "utf-8"),
    );
    const baseName = path.basename(file, ".json");
    const result = await compile(schema, baseName, {
      bannerComment: "",
      style: {
        bracketSpacing: true,
        printWidth: 100,
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "all",
        useTabs: false,
      },
    });
    const outPath = path.join(TEMP_DIR, `${baseName}.ts`);
    fs.writeFileSync(outPath, `${BANNER}${result.trim()}\n`);
    console.log("Generated:", outPath);
  }

  const indexContent = files
    .map((f) => `export type * from "./${path.basename(f, ".json")}.js";`)
    .join("\n");
  fs.writeFileSync(
    path.join(TEMP_DIR, "index.ts"),
    `${BANNER}${indexContent}\n`,
  );
  console.log("Generated:", path.join(TEMP_DIR, "index.ts"));
  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
